

server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      master:
        default-package: com.example.demo.dao
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      second:
        default-package: com.example.demo.dao
        username: root
        password: root
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8




  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0

mybatis:
  mapper-locations: classpath:com/example/demo/mapping/*.xml
  type-aliases-package: com.example.demo.pojo